import { useCallback, useState } from 'react'

import type { AiReport, IncidentData } from '@/types'

const SEVERITY_THRESHOLDS = {
  high: 400,
  medium: 200,
}

export function useAiReport() {
  const [report, setReport] = useState<AiReport | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const generate = useCallback(async (incident: IncidentData) => {
    setIsLoading(true)
    setError(null)

    try {
      await new Promise((resolve) => setTimeout(resolve, 600))
      const severity =
        incident.narrative.length > SEVERITY_THRESHOLDS.high
          ? 'high'
          : incident.narrative.length > SEVERITY_THRESHOLDS.medium
          ? 'medium'
          : 'low'

      const generated: AiReport = {
        category: incident.jurisdiction ? 'Legal review' : 'General report',
        severity,
        summary:
          incident.narrative ||
          'No narrative provided. Please add more details for a better summary.',
        legal:
          'This autogenerated summary does not constitute legal advice. Share the full incident with your counsel if you need legal guidance.',
      }

      setReport(generated)
      return generated
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unable to run AI summary')
      throw err
    } finally {
      setIsLoading(false)
    }
  }, [])

  return { report, isLoading, error, generate }
}
